import pandas as pd, sys
sys.stdout.reconfigure(encoding='utf-8')
df_p = pd.read_parquet('data/processed/hourly.parquet')
print('PRICE columns:', df_p.columns.tolist())
print('Shape:', df_p.shape)
print('Index:', df_p.index.min(), '->', df_p.index.max())
print()
df_l = pd.read_parquet('data/processed/hourly_load.parquet')
print('LOAD columns:', df_l.columns.tolist())
print('Shape:', df_l.shape)
print('Index:', df_l.index.min(), '->', df_l.index.max())
print()
print('PRICE sample:')
print(df_p[['y']].describe())
print()
print('LOAD sample:')
print(df_l[['y']].describe())
