import React, { useState, useEffect } from 'react';
import { Sidebar } from './components/Sidebar';
import { PredictionChart } from './components/PredictionChart';
import { MetricTable } from './components/MetricTable';
import { TargetVariable, PredictionTechnique, ExperimentData } from './types';
import { generateMockData } from './constants';

const App: React.FC = () => {
  const [target, setTarget] = useState<TargetVariable>(TargetVariable.PRICE);
  const [technique, setTechnique] = useState<PredictionTechnique>(PredictionTechnique.RECURSIVE_CLOSED);
  const [data, setData] = useState<ExperimentData | null>(null);
  const [loading, setLoading] = useState<boolean>(true);

  // Load data strategy:
  // 1. Try to fetch 'results.json' (generated by Python).
  // 2. If not found, fall back to Mock Data.
  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      try {
        // Try to fetch a local file named 'results.json' which Python exports
        const response = await fetch('./results.json');
        if (response.ok) {
          const json = await response.json();
          setData(json);
          // Sync UI state with loaded data
          if (json.target) setTarget(json.target);
          if (json.technique) setTechnique(json.technique);
          console.log("Successfully loaded Python results.");
        } else {
          throw new Error("No local results found");
        }
      } catch (error) {
        // Fallback to mock data if no python results exist yet
        console.log("Using scientific mock data (No results.json found).");
        const mock = generateMockData(target, technique);
        setData(mock);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [target, technique]); // Re-run if user manually switches context, though usually file load overrides this.

  // Handle manual file upload override
  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const json = JSON.parse(e.target?.result as string);
        setData(json);
        if(json.target) setTarget(json.target);
        if(json.technique) setTechnique(json.technique);
      } catch (error) {
        alert("Error parsing JSON file. Please ensure it matches the ExperimentData schema.");
      }
    };
    reader.readAsText(file);
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 flex font-sans">
      
      <Sidebar 
        currentTarget={target}
        currentTechnique={technique}
        onSelectTarget={setTarget}
        onSelectTechnique={setTechnique}
        onFileUpload={handleFileUpload}
      />

      <main className="ml-72 flex-1 p-8 overflow-y-auto h-screen">
        <header className="mb-8 flex justify-between items-end border-b border-slate-800 pb-6">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider border ${
                target === TargetVariable.PRICE 
                  ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' 
                  : 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20'
              }`}>
                {target} Forecasting
              </span>
              <span className="text-slate-600">/</span>
              <span className="text-xs font-mono text-slate-400">{technique}</span>
            </div>
            <h2 className="text-3xl font-bold text-white tracking-tight">
              Model Performance Analysis
            </h2>
            <p className="text-slate-500 mt-2 text-sm max-w-2xl">
              Comparative visualization of AI models (LGBM, XGBoost, SVR, MLP, RF) against statistical baselines.
              Data generated via {technique.toLowerCase()}.
            </p>
          </div>
        </header>

        {data && !loading ? (
          <div className="space-y-8 animate-fade-in">
            
            {/* Chart Section */}
            <section className="bg-slate-900/50 rounded-xl border border-slate-800/50 p-1">
              <div className="p-4 border-b border-slate-800/50 flex justify-between items-center">
                 <h3 className="font-semibold text-slate-300 flex items-center gap-2">
                   <span className="w-1.5 h-1.5 rounded-full bg-indigo-500"></span>
                   Forecast vs Actual
                 </h3>
                 <span className="text-xs font-mono text-slate-500">
                   Horizon: {data.data.length} hours
                 </span>
              </div>
              <div className="p-6">
                <PredictionChart data={data.data} target={target} />
              </div>
            </section>

            {/* Metrics Section */}
            <section>
              <MetricTable metrics={data.metrics} />
            </section>

          </div>
        ) : (
          <div className="flex flex-col items-center justify-center h-96 text-slate-500 animate-pulse">
             <div className="w-8 h-8 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin mb-4"></div>
             <p className="font-mono text-sm">Processing experimental results...</p>
          </div>
        )}
      </main>
    </div>
  );
};

export default App;
